#ChipScope Core Inserter Project File Version 3.0
#Wed Apr 23 14:53:54 CST 2014
Project.device.designInputFile=G\:\\pcie_server\\HKADS-13-05B-IP-0208_taixin\\ise\\pcie_dma_ep_top_cs.ngc
Project.device.designOutputFile=G\:\\pcie_server\\HKADS-13-05B-IP-0208_taixin\\ise\\pcie_dma_ep_top_cs.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=G\:\\pcie_server\\HKADS-13-05B-IP-0208_taixin\\ise\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=9
Project.filter<0>=
Project.filter<1>=trn_rrem_n*
Project.filter<2>=trn_reof_n*
Project.filter<3>=trn_rsof_n*
Project.filter<4>=trn_rd*
Project.filter<5>=dma_r*
Project.filter<6>=dma_w*
Project.filter<7>=dma_waddr_en*
Project.filter<8>=trn_clk*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=xpcie_dma_core_ep trn_clkout
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=xpcie_dma_core_ep dma_waddr<0>
Project.unit<0>.dataChannel<100>=xpcie_dma_core_ep dma_write_start
Project.unit<0>.dataChannel<101>=xpcie_dma_core_ep dma_raddr<0>
Project.unit<0>.dataChannel<102>=xpcie_dma_core_ep dma_raddr<1>
Project.unit<0>.dataChannel<103>=xpcie_dma_core_ep dma_raddr<2>
Project.unit<0>.dataChannel<104>=xpcie_dma_core_ep dma_raddr<3>
Project.unit<0>.dataChannel<105>=xpcie_dma_core_ep dma_raddr<4>
Project.unit<0>.dataChannel<106>=xpcie_dma_core_ep dma_raddr<5>
Project.unit<0>.dataChannel<107>=xpcie_dma_core_ep dma_raddr<6>
Project.unit<0>.dataChannel<108>=xpcie_dma_core_ep dma_raddr<7>
Project.unit<0>.dataChannel<109>=xpcie_dma_core_ep dma_raddr<8>
Project.unit<0>.dataChannel<10>=xpcie_dma_core_ep dma_waddr<10>
Project.unit<0>.dataChannel<110>=xpcie_dma_core_ep dma_raddr<9>
Project.unit<0>.dataChannel<111>=xpcie_dma_core_ep dma_raddr<10>
Project.unit<0>.dataChannel<112>=xpcie_dma_core_ep dma_raddr<11>
Project.unit<0>.dataChannel<113>=xpcie_dma_core_ep dma_raddr<12>
Project.unit<0>.dataChannel<114>=xpcie_dma_core_ep dma_raddr<13>
Project.unit<0>.dataChannel<115>=xpcie_dma_core_ep dma_raddr<14>
Project.unit<0>.dataChannel<116>=xpcie_dma_core_ep dma_raddr<15>
Project.unit<0>.dataChannel<117>=xpcie_dma_core_ep dma_raddr<16>
Project.unit<0>.dataChannel<118>=xpcie_dma_core_ep dma_raddr<17>
Project.unit<0>.dataChannel<119>=xpcie_dma_core_ep dma_raddr<18>
Project.unit<0>.dataChannel<11>=xpcie_dma_core_ep dma_waddr<11>
Project.unit<0>.dataChannel<120>=xpcie_dma_core_ep dma_raddr<19>
Project.unit<0>.dataChannel<121>=xpcie_dma_core_ep dma_raddr<20>
Project.unit<0>.dataChannel<122>=xpcie_dma_core_ep dma_raddr<21>
Project.unit<0>.dataChannel<123>=xpcie_dma_core_ep dma_raddr<22>
Project.unit<0>.dataChannel<124>=xpcie_dma_core_ep dma_raddr<23>
Project.unit<0>.dataChannel<125>=xpcie_dma_core_ep dma_raddr<24>
Project.unit<0>.dataChannel<126>=xpcie_dma_core_ep dma_raddr<25>
Project.unit<0>.dataChannel<127>=xpcie_dma_core_ep dma_raddr<26>
Project.unit<0>.dataChannel<128>=xpcie_dma_core_ep dma_raddr<27>
Project.unit<0>.dataChannel<129>=xpcie_dma_core_ep dma_raddr<28>
Project.unit<0>.dataChannel<12>=xpcie_dma_core_ep dma_waddr<12>
Project.unit<0>.dataChannel<130>=xpcie_dma_core_ep dma_raddr<29>
Project.unit<0>.dataChannel<131>=xpcie_dma_core_ep dma_raddr<30>
Project.unit<0>.dataChannel<132>=xpcie_dma_core_ep dma_raddr<31>
Project.unit<0>.dataChannel<133>=xpcie_dma_core_ep dma_raddr_en
Project.unit<0>.dataChannel<134>=xpcie_dma_core_ep dma_rdata<0>
Project.unit<0>.dataChannel<135>=xpcie_dma_core_ep dma_rdata<1>
Project.unit<0>.dataChannel<136>=xpcie_dma_core_ep dma_rdata<2>
Project.unit<0>.dataChannel<137>=xpcie_dma_core_ep dma_rdata<3>
Project.unit<0>.dataChannel<138>=xpcie_dma_core_ep dma_rdata<4>
Project.unit<0>.dataChannel<139>=xpcie_dma_core_ep dma_rdata<5>
Project.unit<0>.dataChannel<13>=xpcie_dma_core_ep dma_waddr<13>
Project.unit<0>.dataChannel<140>=xpcie_dma_core_ep dma_rdata<6>
Project.unit<0>.dataChannel<141>=xpcie_dma_core_ep dma_rdata<7>
Project.unit<0>.dataChannel<142>=xpcie_dma_core_ep dma_rdata<8>
Project.unit<0>.dataChannel<143>=xpcie_dma_core_ep dma_rdata<9>
Project.unit<0>.dataChannel<144>=xpcie_dma_core_ep dma_rdata<10>
Project.unit<0>.dataChannel<145>=xpcie_dma_core_ep dma_rdata<11>
Project.unit<0>.dataChannel<146>=xpcie_dma_core_ep dma_rdata<12>
Project.unit<0>.dataChannel<147>=xpcie_dma_core_ep dma_rdata<13>
Project.unit<0>.dataChannel<148>=xpcie_dma_core_ep dma_rdata<14>
Project.unit<0>.dataChannel<149>=xpcie_dma_core_ep dma_rdata<15>
Project.unit<0>.dataChannel<14>=xpcie_dma_core_ep dma_waddr<14>
Project.unit<0>.dataChannel<150>=xpcie_dma_core_ep dma_rdata<16>
Project.unit<0>.dataChannel<151>=xpcie_dma_core_ep dma_rdata<17>
Project.unit<0>.dataChannel<152>=xpcie_dma_core_ep dma_rdata<18>
Project.unit<0>.dataChannel<153>=xpcie_dma_core_ep dma_rdata<19>
Project.unit<0>.dataChannel<154>=xpcie_dma_core_ep dma_rdata<20>
Project.unit<0>.dataChannel<155>=xpcie_dma_core_ep dma_rdata<21>
Project.unit<0>.dataChannel<156>=xpcie_dma_core_ep dma_rdata<22>
Project.unit<0>.dataChannel<157>=xpcie_dma_core_ep dma_rdata<23>
Project.unit<0>.dataChannel<158>=xpcie_dma_core_ep dma_rdata<24>
Project.unit<0>.dataChannel<159>=xpcie_dma_core_ep dma_rdata<25>
Project.unit<0>.dataChannel<15>=xpcie_dma_core_ep dma_waddr<15>
Project.unit<0>.dataChannel<160>=xpcie_dma_core_ep dma_rdata<26>
Project.unit<0>.dataChannel<161>=xpcie_dma_core_ep dma_rdata<27>
Project.unit<0>.dataChannel<162>=xpcie_dma_core_ep dma_rdata<28>
Project.unit<0>.dataChannel<163>=xpcie_dma_core_ep dma_rdata<29>
Project.unit<0>.dataChannel<164>=xpcie_dma_core_ep dma_rdata<30>
Project.unit<0>.dataChannel<165>=xpcie_dma_core_ep dma_rdata<31>
Project.unit<0>.dataChannel<166>=xpcie_dma_core_ep dma_rdata<32>
Project.unit<0>.dataChannel<167>=xpcie_dma_core_ep dma_rdata<33>
Project.unit<0>.dataChannel<168>=xpcie_dma_core_ep dma_rdata<34>
Project.unit<0>.dataChannel<169>=xpcie_dma_core_ep dma_rdata<35>
Project.unit<0>.dataChannel<16>=xpcie_dma_core_ep dma_waddr<16>
Project.unit<0>.dataChannel<170>=xpcie_dma_core_ep dma_rdata<36>
Project.unit<0>.dataChannel<171>=xpcie_dma_core_ep dma_rdata<37>
Project.unit<0>.dataChannel<172>=xpcie_dma_core_ep dma_rdata<38>
Project.unit<0>.dataChannel<173>=xpcie_dma_core_ep dma_rdata<39>
Project.unit<0>.dataChannel<174>=xpcie_dma_core_ep dma_rdata<40>
Project.unit<0>.dataChannel<175>=xpcie_dma_core_ep dma_rdata<41>
Project.unit<0>.dataChannel<176>=xpcie_dma_core_ep dma_rdata<42>
Project.unit<0>.dataChannel<177>=xpcie_dma_core_ep dma_rdata<43>
Project.unit<0>.dataChannel<178>=xpcie_dma_core_ep dma_rdata<44>
Project.unit<0>.dataChannel<179>=xpcie_dma_core_ep dma_rdata<45>
Project.unit<0>.dataChannel<17>=xpcie_dma_core_ep dma_waddr<17>
Project.unit<0>.dataChannel<180>=xpcie_dma_core_ep dma_rdata<46>
Project.unit<0>.dataChannel<181>=xpcie_dma_core_ep dma_rdata<47>
Project.unit<0>.dataChannel<182>=xpcie_dma_core_ep dma_rdata<48>
Project.unit<0>.dataChannel<183>=xpcie_dma_core_ep dma_rdata<49>
Project.unit<0>.dataChannel<184>=xpcie_dma_core_ep dma_rdata<50>
Project.unit<0>.dataChannel<185>=xpcie_dma_core_ep dma_rdata<51>
Project.unit<0>.dataChannel<186>=xpcie_dma_core_ep dma_rdata<52>
Project.unit<0>.dataChannel<187>=xpcie_dma_core_ep dma_rdata<53>
Project.unit<0>.dataChannel<188>=xpcie_dma_core_ep dma_rdata<54>
Project.unit<0>.dataChannel<189>=xpcie_dma_core_ep dma_rdata<55>
Project.unit<0>.dataChannel<18>=xpcie_dma_core_ep dma_waddr<18>
Project.unit<0>.dataChannel<190>=xpcie_dma_core_ep dma_rdata<56>
Project.unit<0>.dataChannel<191>=xpcie_dma_core_ep dma_rdata<57>
Project.unit<0>.dataChannel<192>=xpcie_dma_core_ep dma_rdata<58>
Project.unit<0>.dataChannel<193>=xpcie_dma_core_ep dma_rdata<59>
Project.unit<0>.dataChannel<194>=xpcie_dma_core_ep dma_rdata<60>
Project.unit<0>.dataChannel<195>=xpcie_dma_core_ep dma_rdata<61>
Project.unit<0>.dataChannel<196>=xpcie_dma_core_ep dma_rdata<62>
Project.unit<0>.dataChannel<197>=xpcie_dma_core_ep dma_rdata<63>
Project.unit<0>.dataChannel<198>=xpcie_dma_core_ep dma_rdata_busy
Project.unit<0>.dataChannel<199>=xpcie_dma_core_ep dma_rdata_en
Project.unit<0>.dataChannel<19>=xpcie_dma_core_ep dma_waddr<19>
Project.unit<0>.dataChannel<1>=xpcie_dma_core_ep dma_waddr<1>
Project.unit<0>.dataChannel<200>=xpcie_dma_core_ep dma_rdata_rdy
Project.unit<0>.dataChannel<201>=xpcie_dma_core_ep dma_read_end
Project.unit<0>.dataChannel<202>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<0>
Project.unit<0>.dataChannel<203>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<1>
Project.unit<0>.dataChannel<204>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<2>
Project.unit<0>.dataChannel<205>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<3>
Project.unit<0>.dataChannel<206>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<4>
Project.unit<0>.dataChannel<207>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<5>
Project.unit<0>.dataChannel<208>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<6>
Project.unit<0>.dataChannel<209>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<7>
Project.unit<0>.dataChannel<20>=xpcie_dma_core_ep dma_waddr<20>
Project.unit<0>.dataChannel<210>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<8>
Project.unit<0>.dataChannel<211>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<9>
Project.unit<0>.dataChannel<212>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<10>
Project.unit<0>.dataChannel<213>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<11>
Project.unit<0>.dataChannel<214>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<12>
Project.unit<0>.dataChannel<215>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<13>
Project.unit<0>.dataChannel<216>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<14>
Project.unit<0>.dataChannel<217>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<15>
Project.unit<0>.dataChannel<218>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<16>
Project.unit<0>.dataChannel<219>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<17>
Project.unit<0>.dataChannel<21>=xpcie_dma_core_ep dma_waddr<21>
Project.unit<0>.dataChannel<220>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<18>
Project.unit<0>.dataChannel<221>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<19>
Project.unit<0>.dataChannel<222>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<20>
Project.unit<0>.dataChannel<223>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<21>
Project.unit<0>.dataChannel<224>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<22>
Project.unit<0>.dataChannel<225>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<23>
Project.unit<0>.dataChannel<226>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<24>
Project.unit<0>.dataChannel<227>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<25>
Project.unit<0>.dataChannel<228>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<26>
Project.unit<0>.dataChannel<229>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<27>
Project.unit<0>.dataChannel<22>=xpcie_dma_core_ep dma_waddr<22>
Project.unit<0>.dataChannel<230>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<28>
Project.unit<0>.dataChannel<231>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<29>
Project.unit<0>.dataChannel<232>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<30>
Project.unit<0>.dataChannel<233>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<31>
Project.unit<0>.dataChannel<234>=xpcie_dma_core_ep app PCIE_DMA dma_wdata_en
Project.unit<0>.dataChannel<235>=xpcie_dma_core_ep app PCIE_DMA dma_wdata_rdy
Project.unit<0>.dataChannel<236>=xpcie_dma_core_ep app PCIE_DMA dma_write_end
Project.unit<0>.dataChannel<237>=xpcie_dma_core_ep app PCIE_DMA dma_write_start
Project.unit<0>.dataChannel<238>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<0>
Project.unit<0>.dataChannel<239>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<1>
Project.unit<0>.dataChannel<23>=xpcie_dma_core_ep dma_waddr<23>
Project.unit<0>.dataChannel<240>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<2>
Project.unit<0>.dataChannel<241>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<3>
Project.unit<0>.dataChannel<242>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<4>
Project.unit<0>.dataChannel<243>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<5>
Project.unit<0>.dataChannel<244>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<6>
Project.unit<0>.dataChannel<245>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<7>
Project.unit<0>.dataChannel<246>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<8>
Project.unit<0>.dataChannel<247>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<9>
Project.unit<0>.dataChannel<248>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<10>
Project.unit<0>.dataChannel<249>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<11>
Project.unit<0>.dataChannel<24>=xpcie_dma_core_ep dma_waddr<24>
Project.unit<0>.dataChannel<250>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<12>
Project.unit<0>.dataChannel<251>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<13>
Project.unit<0>.dataChannel<252>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<14>
Project.unit<0>.dataChannel<253>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<15>
Project.unit<0>.dataChannel<254>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<16>
Project.unit<0>.dataChannel<255>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<17>
Project.unit<0>.dataChannel<256>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<18>
Project.unit<0>.dataChannel<257>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<19>
Project.unit<0>.dataChannel<258>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<20>
Project.unit<0>.dataChannel<259>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<21>
Project.unit<0>.dataChannel<25>=xpcie_dma_core_ep dma_waddr<25>
Project.unit<0>.dataChannel<260>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<22>
Project.unit<0>.dataChannel<261>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<23>
Project.unit<0>.dataChannel<262>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<24>
Project.unit<0>.dataChannel<263>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<25>
Project.unit<0>.dataChannel<264>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<26>
Project.unit<0>.dataChannel<265>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<27>
Project.unit<0>.dataChannel<266>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<28>
Project.unit<0>.dataChannel<267>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<29>
Project.unit<0>.dataChannel<268>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<30>
Project.unit<0>.dataChannel<269>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<31>
Project.unit<0>.dataChannel<26>=xpcie_dma_core_ep dma_waddr<26>
Project.unit<0>.dataChannel<270>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<32>
Project.unit<0>.dataChannel<271>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<33>
Project.unit<0>.dataChannel<272>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<34>
Project.unit<0>.dataChannel<273>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<35>
Project.unit<0>.dataChannel<274>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<36>
Project.unit<0>.dataChannel<275>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<37>
Project.unit<0>.dataChannel<276>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<38>
Project.unit<0>.dataChannel<277>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<39>
Project.unit<0>.dataChannel<278>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<40>
Project.unit<0>.dataChannel<279>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<41>
Project.unit<0>.dataChannel<27>=xpcie_dma_core_ep dma_waddr<27>
Project.unit<0>.dataChannel<280>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<42>
Project.unit<0>.dataChannel<281>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<43>
Project.unit<0>.dataChannel<282>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<44>
Project.unit<0>.dataChannel<283>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<45>
Project.unit<0>.dataChannel<284>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<46>
Project.unit<0>.dataChannel<285>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<47>
Project.unit<0>.dataChannel<286>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<48>
Project.unit<0>.dataChannel<287>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<49>
Project.unit<0>.dataChannel<288>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<50>
Project.unit<0>.dataChannel<289>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<51>
Project.unit<0>.dataChannel<28>=xpcie_dma_core_ep dma_waddr<28>
Project.unit<0>.dataChannel<290>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<52>
Project.unit<0>.dataChannel<291>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<53>
Project.unit<0>.dataChannel<292>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<54>
Project.unit<0>.dataChannel<293>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<55>
Project.unit<0>.dataChannel<294>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<56>
Project.unit<0>.dataChannel<295>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<57>
Project.unit<0>.dataChannel<296>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<58>
Project.unit<0>.dataChannel<297>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<59>
Project.unit<0>.dataChannel<298>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<60>
Project.unit<0>.dataChannel<299>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<61>
Project.unit<0>.dataChannel<29>=xpcie_dma_core_ep dma_waddr<29>
Project.unit<0>.dataChannel<2>=xpcie_dma_core_ep dma_waddr<2>
Project.unit<0>.dataChannel<300>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<62>
Project.unit<0>.dataChannel<301>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<63>
Project.unit<0>.dataChannel<302>=xpcie_dma_core_ep app PCIE_DMA dma_rdata_busy
Project.unit<0>.dataChannel<303>=xpcie_dma_core_ep app PCIE_DMA dma_rdata_en
Project.unit<0>.dataChannel<304>=xpcie_dma_core_ep app PCIE_DMA dma_read_end
Project.unit<0>.dataChannel<305>=xpcie_dma_core_ep app PCIE_DMA dma_read_start
Project.unit<0>.dataChannel<306>=xpcie_dma_core_ep app PCIE_DMA dma_reset
Project.unit<0>.dataChannel<307>=xpcie_dma_core_ep app PCIE_DMA trn_rd<0>
Project.unit<0>.dataChannel<308>=xpcie_dma_core_ep app PCIE_DMA trn_rd<1>
Project.unit<0>.dataChannel<309>=xpcie_dma_core_ep app PCIE_DMA trn_rd<2>
Project.unit<0>.dataChannel<30>=xpcie_dma_core_ep dma_waddr<30>
Project.unit<0>.dataChannel<310>=xpcie_dma_core_ep app PCIE_DMA trn_rd<3>
Project.unit<0>.dataChannel<311>=xpcie_dma_core_ep app PCIE_DMA trn_rd<4>
Project.unit<0>.dataChannel<312>=xpcie_dma_core_ep app PCIE_DMA trn_rd<5>
Project.unit<0>.dataChannel<313>=xpcie_dma_core_ep app PCIE_DMA trn_rd<6>
Project.unit<0>.dataChannel<314>=xpcie_dma_core_ep app PCIE_DMA trn_rd<7>
Project.unit<0>.dataChannel<315>=xpcie_dma_core_ep app PCIE_DMA trn_rd<8>
Project.unit<0>.dataChannel<316>=xpcie_dma_core_ep app PCIE_DMA trn_rd<9>
Project.unit<0>.dataChannel<317>=xpcie_dma_core_ep app PCIE_DMA trn_rd<10>
Project.unit<0>.dataChannel<318>=xpcie_dma_core_ep app PCIE_DMA trn_rd<11>
Project.unit<0>.dataChannel<319>=xpcie_dma_core_ep app PCIE_DMA trn_rd<12>
Project.unit<0>.dataChannel<31>=xpcie_dma_core_ep dma_waddr<31>
Project.unit<0>.dataChannel<320>=xpcie_dma_core_ep app PCIE_DMA trn_rd<13>
Project.unit<0>.dataChannel<321>=xpcie_dma_core_ep app PCIE_DMA trn_rd<14>
Project.unit<0>.dataChannel<322>=xpcie_dma_core_ep app PCIE_DMA trn_rd<15>
Project.unit<0>.dataChannel<323>=xpcie_dma_core_ep app PCIE_DMA trn_rd<16>
Project.unit<0>.dataChannel<324>=xpcie_dma_core_ep app PCIE_DMA trn_rd<17>
Project.unit<0>.dataChannel<325>=xpcie_dma_core_ep app PCIE_DMA trn_rd<18>
Project.unit<0>.dataChannel<326>=xpcie_dma_core_ep app PCIE_DMA trn_rd<19>
Project.unit<0>.dataChannel<327>=xpcie_dma_core_ep app PCIE_DMA trn_rd<20>
Project.unit<0>.dataChannel<328>=xpcie_dma_core_ep app PCIE_DMA trn_rd<21>
Project.unit<0>.dataChannel<329>=xpcie_dma_core_ep app PCIE_DMA trn_rd<22>
Project.unit<0>.dataChannel<32>=xpcie_dma_core_ep dma_waddr_en
Project.unit<0>.dataChannel<330>=xpcie_dma_core_ep app PCIE_DMA trn_rd<23>
Project.unit<0>.dataChannel<331>=xpcie_dma_core_ep app PCIE_DMA trn_rd<24>
Project.unit<0>.dataChannel<332>=xpcie_dma_core_ep app PCIE_DMA trn_rd<25>
Project.unit<0>.dataChannel<333>=xpcie_dma_core_ep app PCIE_DMA trn_rd<26>
Project.unit<0>.dataChannel<334>=xpcie_dma_core_ep app PCIE_DMA trn_rd<27>
Project.unit<0>.dataChannel<335>=xpcie_dma_core_ep app PCIE_DMA trn_rd<28>
Project.unit<0>.dataChannel<336>=xpcie_dma_core_ep app PCIE_DMA trn_rd<29>
Project.unit<0>.dataChannel<337>=xpcie_dma_core_ep app PCIE_DMA trn_rd<30>
Project.unit<0>.dataChannel<338>=xpcie_dma_core_ep app PCIE_DMA trn_rd<31>
Project.unit<0>.dataChannel<339>=xpcie_dma_core_ep app PCIE_DMA trn_rd<32>
Project.unit<0>.dataChannel<33>=xpcie_dma_core_ep dma_wdata<0>
Project.unit<0>.dataChannel<340>=xpcie_dma_core_ep app PCIE_DMA trn_rd<33>
Project.unit<0>.dataChannel<341>=xpcie_dma_core_ep app PCIE_DMA trn_rd<34>
Project.unit<0>.dataChannel<342>=xpcie_dma_core_ep app PCIE_DMA trn_rd<35>
Project.unit<0>.dataChannel<343>=xpcie_dma_core_ep app PCIE_DMA trn_rd<36>
Project.unit<0>.dataChannel<344>=xpcie_dma_core_ep app PCIE_DMA trn_rd<37>
Project.unit<0>.dataChannel<345>=xpcie_dma_core_ep app PCIE_DMA trn_rd<38>
Project.unit<0>.dataChannel<346>=xpcie_dma_core_ep app PCIE_DMA trn_rd<39>
Project.unit<0>.dataChannel<347>=xpcie_dma_core_ep app PCIE_DMA trn_rd<40>
Project.unit<0>.dataChannel<348>=xpcie_dma_core_ep app PCIE_DMA trn_rd<41>
Project.unit<0>.dataChannel<349>=xpcie_dma_core_ep app PCIE_DMA trn_rd<42>
Project.unit<0>.dataChannel<34>=xpcie_dma_core_ep dma_wdata<1>
Project.unit<0>.dataChannel<350>=xpcie_dma_core_ep app PCIE_DMA trn_rd<43>
Project.unit<0>.dataChannel<351>=xpcie_dma_core_ep app PCIE_DMA trn_rd<44>
Project.unit<0>.dataChannel<352>=xpcie_dma_core_ep app PCIE_DMA trn_rd<45>
Project.unit<0>.dataChannel<353>=xpcie_dma_core_ep app PCIE_DMA trn_rd<46>
Project.unit<0>.dataChannel<354>=xpcie_dma_core_ep app PCIE_DMA trn_rd<47>
Project.unit<0>.dataChannel<355>=xpcie_dma_core_ep app PCIE_DMA trn_rd<48>
Project.unit<0>.dataChannel<356>=xpcie_dma_core_ep app PCIE_DMA trn_rd<49>
Project.unit<0>.dataChannel<357>=xpcie_dma_core_ep app PCIE_DMA trn_rd<50>
Project.unit<0>.dataChannel<358>=xpcie_dma_core_ep app PCIE_DMA trn_rd<51>
Project.unit<0>.dataChannel<359>=xpcie_dma_core_ep app PCIE_DMA trn_rd<52>
Project.unit<0>.dataChannel<35>=xpcie_dma_core_ep dma_wdata<2>
Project.unit<0>.dataChannel<360>=xpcie_dma_core_ep app PCIE_DMA trn_rd<53>
Project.unit<0>.dataChannel<361>=xpcie_dma_core_ep app PCIE_DMA trn_rd<54>
Project.unit<0>.dataChannel<362>=xpcie_dma_core_ep app PCIE_DMA trn_rd<55>
Project.unit<0>.dataChannel<363>=xpcie_dma_core_ep app PCIE_DMA trn_rd<56>
Project.unit<0>.dataChannel<364>=xpcie_dma_core_ep app PCIE_DMA trn_rd<57>
Project.unit<0>.dataChannel<365>=xpcie_dma_core_ep app PCIE_DMA trn_rd<58>
Project.unit<0>.dataChannel<366>=xpcie_dma_core_ep app PCIE_DMA trn_rd<59>
Project.unit<0>.dataChannel<367>=xpcie_dma_core_ep app PCIE_DMA trn_rd<60>
Project.unit<0>.dataChannel<368>=xpcie_dma_core_ep app PCIE_DMA trn_rd<61>
Project.unit<0>.dataChannel<369>=xpcie_dma_core_ep app PCIE_DMA trn_rd<62>
Project.unit<0>.dataChannel<36>=xpcie_dma_core_ep dma_wdata<3>
Project.unit<0>.dataChannel<370>=xpcie_dma_core_ep app PCIE_DMA trn_rd<63>
Project.unit<0>.dataChannel<371>=xpcie_dma_core_ep app PCIE_DMA trn_rsof_n
Project.unit<0>.dataChannel<372>=xpcie_dma_core_ep app PCIE_DMA trn_reof_n
Project.unit<0>.dataChannel<373>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<0>
Project.unit<0>.dataChannel<374>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<1>
Project.unit<0>.dataChannel<375>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<2>
Project.unit<0>.dataChannel<376>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<3>
Project.unit<0>.dataChannel<377>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<4>
Project.unit<0>.dataChannel<378>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<5>
Project.unit<0>.dataChannel<379>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<6>
Project.unit<0>.dataChannel<37>=xpcie_dma_core_ep dma_wdata<4>
Project.unit<0>.dataChannel<380>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<7>
Project.unit<0>.dataChannel<38>=xpcie_dma_core_ep dma_wdata<5>
Project.unit<0>.dataChannel<39>=xpcie_dma_core_ep dma_wdata<6>
Project.unit<0>.dataChannel<3>=xpcie_dma_core_ep dma_waddr<3>
Project.unit<0>.dataChannel<40>=xpcie_dma_core_ep dma_wdata<7>
Project.unit<0>.dataChannel<41>=xpcie_dma_core_ep dma_wdata<8>
Project.unit<0>.dataChannel<42>=xpcie_dma_core_ep dma_wdata<9>
Project.unit<0>.dataChannel<43>=xpcie_dma_core_ep dma_wdata<10>
Project.unit<0>.dataChannel<44>=xpcie_dma_core_ep dma_wdata<11>
Project.unit<0>.dataChannel<45>=xpcie_dma_core_ep dma_wdata<12>
Project.unit<0>.dataChannel<46>=xpcie_dma_core_ep dma_wdata<13>
Project.unit<0>.dataChannel<47>=xpcie_dma_core_ep dma_wdata<14>
Project.unit<0>.dataChannel<48>=xpcie_dma_core_ep dma_wdata<15>
Project.unit<0>.dataChannel<49>=xpcie_dma_core_ep dma_wdata<16>
Project.unit<0>.dataChannel<4>=xpcie_dma_core_ep dma_waddr<4>
Project.unit<0>.dataChannel<50>=xpcie_dma_core_ep dma_wdata<17>
Project.unit<0>.dataChannel<51>=xpcie_dma_core_ep dma_wdata<18>
Project.unit<0>.dataChannel<52>=xpcie_dma_core_ep dma_wdata<19>
Project.unit<0>.dataChannel<53>=xpcie_dma_core_ep dma_wdata<20>
Project.unit<0>.dataChannel<54>=xpcie_dma_core_ep dma_wdata<21>
Project.unit<0>.dataChannel<55>=xpcie_dma_core_ep dma_wdata<22>
Project.unit<0>.dataChannel<56>=xpcie_dma_core_ep dma_wdata<23>
Project.unit<0>.dataChannel<57>=xpcie_dma_core_ep dma_wdata<24>
Project.unit<0>.dataChannel<58>=xpcie_dma_core_ep dma_wdata<25>
Project.unit<0>.dataChannel<59>=xpcie_dma_core_ep dma_wdata<26>
Project.unit<0>.dataChannel<5>=xpcie_dma_core_ep dma_waddr<5>
Project.unit<0>.dataChannel<60>=xpcie_dma_core_ep dma_wdata<27>
Project.unit<0>.dataChannel<61>=xpcie_dma_core_ep dma_wdata<28>
Project.unit<0>.dataChannel<62>=xpcie_dma_core_ep dma_wdata<29>
Project.unit<0>.dataChannel<63>=xpcie_dma_core_ep dma_wdata<30>
Project.unit<0>.dataChannel<64>=xpcie_dma_core_ep dma_wdata<31>
Project.unit<0>.dataChannel<65>=xpcie_dma_core_ep dma_wdata<32>
Project.unit<0>.dataChannel<66>=xpcie_dma_core_ep dma_wdata<33>
Project.unit<0>.dataChannel<67>=xpcie_dma_core_ep dma_wdata<34>
Project.unit<0>.dataChannel<68>=xpcie_dma_core_ep dma_wdata<35>
Project.unit<0>.dataChannel<69>=xpcie_dma_core_ep dma_wdata<36>
Project.unit<0>.dataChannel<6>=xpcie_dma_core_ep dma_waddr<6>
Project.unit<0>.dataChannel<70>=xpcie_dma_core_ep dma_wdata<37>
Project.unit<0>.dataChannel<71>=xpcie_dma_core_ep dma_wdata<38>
Project.unit<0>.dataChannel<72>=xpcie_dma_core_ep dma_wdata<39>
Project.unit<0>.dataChannel<73>=xpcie_dma_core_ep dma_wdata<40>
Project.unit<0>.dataChannel<74>=xpcie_dma_core_ep dma_wdata<41>
Project.unit<0>.dataChannel<75>=xpcie_dma_core_ep dma_wdata<42>
Project.unit<0>.dataChannel<76>=xpcie_dma_core_ep dma_wdata<43>
Project.unit<0>.dataChannel<77>=xpcie_dma_core_ep dma_wdata<44>
Project.unit<0>.dataChannel<78>=xpcie_dma_core_ep dma_wdata<45>
Project.unit<0>.dataChannel<79>=xpcie_dma_core_ep dma_wdata<46>
Project.unit<0>.dataChannel<7>=xpcie_dma_core_ep dma_waddr<7>
Project.unit<0>.dataChannel<80>=xpcie_dma_core_ep dma_wdata<47>
Project.unit<0>.dataChannel<81>=xpcie_dma_core_ep dma_wdata<48>
Project.unit<0>.dataChannel<82>=xpcie_dma_core_ep dma_wdata<49>
Project.unit<0>.dataChannel<83>=xpcie_dma_core_ep dma_wdata<50>
Project.unit<0>.dataChannel<84>=xpcie_dma_core_ep dma_wdata<51>
Project.unit<0>.dataChannel<85>=xpcie_dma_core_ep dma_wdata<52>
Project.unit<0>.dataChannel<86>=xpcie_dma_core_ep dma_wdata<53>
Project.unit<0>.dataChannel<87>=xpcie_dma_core_ep dma_wdata<54>
Project.unit<0>.dataChannel<88>=xpcie_dma_core_ep dma_wdata<55>
Project.unit<0>.dataChannel<89>=xpcie_dma_core_ep dma_wdata<56>
Project.unit<0>.dataChannel<8>=xpcie_dma_core_ep dma_waddr<8>
Project.unit<0>.dataChannel<90>=xpcie_dma_core_ep dma_wdata<57>
Project.unit<0>.dataChannel<91>=xpcie_dma_core_ep dma_wdata<58>
Project.unit<0>.dataChannel<92>=xpcie_dma_core_ep dma_wdata<59>
Project.unit<0>.dataChannel<93>=xpcie_dma_core_ep dma_wdata<60>
Project.unit<0>.dataChannel<94>=xpcie_dma_core_ep dma_wdata<61>
Project.unit<0>.dataChannel<95>=xpcie_dma_core_ep dma_wdata<62>
Project.unit<0>.dataChannel<96>=xpcie_dma_core_ep dma_wdata<63>
Project.unit<0>.dataChannel<97>=xpcie_dma_core_ep dma_wdata_en
Project.unit<0>.dataChannel<98>=xpcie_dma_core_ep dma_wdata_rdy
Project.unit<0>.dataChannel<99>=xpcie_dma_core_ep dma_write_end
Project.unit<0>.dataChannel<9>=xpcie_dma_core_ep dma_waddr<9>
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=381
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=xpcie_dma_core_ep dma_waddr<0>
Project.unit<0>.triggerChannel<0><100>=xpcie_dma_core_ep dma_write_start
Project.unit<0>.triggerChannel<0><10>=xpcie_dma_core_ep dma_waddr<10>
Project.unit<0>.triggerChannel<0><11>=xpcie_dma_core_ep dma_waddr<11>
Project.unit<0>.triggerChannel<0><12>=xpcie_dma_core_ep dma_waddr<12>
Project.unit<0>.triggerChannel<0><13>=xpcie_dma_core_ep dma_waddr<13>
Project.unit<0>.triggerChannel<0><14>=xpcie_dma_core_ep dma_waddr<14>
Project.unit<0>.triggerChannel<0><15>=xpcie_dma_core_ep dma_waddr<15>
Project.unit<0>.triggerChannel<0><16>=xpcie_dma_core_ep dma_waddr<16>
Project.unit<0>.triggerChannel<0><17>=xpcie_dma_core_ep dma_waddr<17>
Project.unit<0>.triggerChannel<0><18>=xpcie_dma_core_ep dma_waddr<18>
Project.unit<0>.triggerChannel<0><19>=xpcie_dma_core_ep dma_waddr<19>
Project.unit<0>.triggerChannel<0><1>=xpcie_dma_core_ep dma_waddr<1>
Project.unit<0>.triggerChannel<0><20>=xpcie_dma_core_ep dma_waddr<20>
Project.unit<0>.triggerChannel<0><21>=xpcie_dma_core_ep dma_waddr<21>
Project.unit<0>.triggerChannel<0><22>=xpcie_dma_core_ep dma_waddr<22>
Project.unit<0>.triggerChannel<0><23>=xpcie_dma_core_ep dma_waddr<23>
Project.unit<0>.triggerChannel<0><24>=xpcie_dma_core_ep dma_waddr<24>
Project.unit<0>.triggerChannel<0><25>=xpcie_dma_core_ep dma_waddr<25>
Project.unit<0>.triggerChannel<0><26>=xpcie_dma_core_ep dma_waddr<26>
Project.unit<0>.triggerChannel<0><27>=xpcie_dma_core_ep dma_waddr<27>
Project.unit<0>.triggerChannel<0><28>=xpcie_dma_core_ep dma_waddr<28>
Project.unit<0>.triggerChannel<0><29>=xpcie_dma_core_ep dma_waddr<29>
Project.unit<0>.triggerChannel<0><2>=xpcie_dma_core_ep dma_waddr<2>
Project.unit<0>.triggerChannel<0><30>=xpcie_dma_core_ep dma_waddr<30>
Project.unit<0>.triggerChannel<0><31>=xpcie_dma_core_ep dma_waddr<31>
Project.unit<0>.triggerChannel<0><32>=xpcie_dma_core_ep dma_waddr_en
Project.unit<0>.triggerChannel<0><33>=xpcie_dma_core_ep dma_wdata<0>
Project.unit<0>.triggerChannel<0><34>=xpcie_dma_core_ep dma_wdata<1>
Project.unit<0>.triggerChannel<0><35>=xpcie_dma_core_ep dma_wdata<2>
Project.unit<0>.triggerChannel<0><36>=xpcie_dma_core_ep dma_wdata<3>
Project.unit<0>.triggerChannel<0><37>=xpcie_dma_core_ep dma_wdata<4>
Project.unit<0>.triggerChannel<0><38>=xpcie_dma_core_ep dma_wdata<5>
Project.unit<0>.triggerChannel<0><39>=xpcie_dma_core_ep dma_wdata<6>
Project.unit<0>.triggerChannel<0><3>=xpcie_dma_core_ep dma_waddr<3>
Project.unit<0>.triggerChannel<0><40>=xpcie_dma_core_ep dma_wdata<7>
Project.unit<0>.triggerChannel<0><41>=xpcie_dma_core_ep dma_wdata<8>
Project.unit<0>.triggerChannel<0><42>=xpcie_dma_core_ep dma_wdata<9>
Project.unit<0>.triggerChannel<0><43>=xpcie_dma_core_ep dma_wdata<10>
Project.unit<0>.triggerChannel<0><44>=xpcie_dma_core_ep dma_wdata<11>
Project.unit<0>.triggerChannel<0><45>=xpcie_dma_core_ep dma_wdata<12>
Project.unit<0>.triggerChannel<0><46>=xpcie_dma_core_ep dma_wdata<13>
Project.unit<0>.triggerChannel<0><47>=xpcie_dma_core_ep dma_wdata<14>
Project.unit<0>.triggerChannel<0><48>=xpcie_dma_core_ep dma_wdata<15>
Project.unit<0>.triggerChannel<0><49>=xpcie_dma_core_ep dma_wdata<16>
Project.unit<0>.triggerChannel<0><4>=xpcie_dma_core_ep dma_waddr<4>
Project.unit<0>.triggerChannel<0><50>=xpcie_dma_core_ep dma_wdata<17>
Project.unit<0>.triggerChannel<0><51>=xpcie_dma_core_ep dma_wdata<18>
Project.unit<0>.triggerChannel<0><52>=xpcie_dma_core_ep dma_wdata<19>
Project.unit<0>.triggerChannel<0><53>=xpcie_dma_core_ep dma_wdata<20>
Project.unit<0>.triggerChannel<0><54>=xpcie_dma_core_ep dma_wdata<21>
Project.unit<0>.triggerChannel<0><55>=xpcie_dma_core_ep dma_wdata<22>
Project.unit<0>.triggerChannel<0><56>=xpcie_dma_core_ep dma_wdata<23>
Project.unit<0>.triggerChannel<0><57>=xpcie_dma_core_ep dma_wdata<24>
Project.unit<0>.triggerChannel<0><58>=xpcie_dma_core_ep dma_wdata<25>
Project.unit<0>.triggerChannel<0><59>=xpcie_dma_core_ep dma_wdata<26>
Project.unit<0>.triggerChannel<0><5>=xpcie_dma_core_ep dma_waddr<5>
Project.unit<0>.triggerChannel<0><60>=xpcie_dma_core_ep dma_wdata<27>
Project.unit<0>.triggerChannel<0><61>=xpcie_dma_core_ep dma_wdata<28>
Project.unit<0>.triggerChannel<0><62>=xpcie_dma_core_ep dma_wdata<29>
Project.unit<0>.triggerChannel<0><63>=xpcie_dma_core_ep dma_wdata<30>
Project.unit<0>.triggerChannel<0><64>=xpcie_dma_core_ep dma_wdata<31>
Project.unit<0>.triggerChannel<0><65>=xpcie_dma_core_ep dma_wdata<32>
Project.unit<0>.triggerChannel<0><66>=xpcie_dma_core_ep dma_wdata<33>
Project.unit<0>.triggerChannel<0><67>=xpcie_dma_core_ep dma_wdata<34>
Project.unit<0>.triggerChannel<0><68>=xpcie_dma_core_ep dma_wdata<35>
Project.unit<0>.triggerChannel<0><69>=xpcie_dma_core_ep dma_wdata<36>
Project.unit<0>.triggerChannel<0><6>=xpcie_dma_core_ep dma_waddr<6>
Project.unit<0>.triggerChannel<0><70>=xpcie_dma_core_ep dma_wdata<37>
Project.unit<0>.triggerChannel<0><71>=xpcie_dma_core_ep dma_wdata<38>
Project.unit<0>.triggerChannel<0><72>=xpcie_dma_core_ep dma_wdata<39>
Project.unit<0>.triggerChannel<0><73>=xpcie_dma_core_ep dma_wdata<40>
Project.unit<0>.triggerChannel<0><74>=xpcie_dma_core_ep dma_wdata<41>
Project.unit<0>.triggerChannel<0><75>=xpcie_dma_core_ep dma_wdata<42>
Project.unit<0>.triggerChannel<0><76>=xpcie_dma_core_ep dma_wdata<43>
Project.unit<0>.triggerChannel<0><77>=xpcie_dma_core_ep dma_wdata<44>
Project.unit<0>.triggerChannel<0><78>=xpcie_dma_core_ep dma_wdata<45>
Project.unit<0>.triggerChannel<0><79>=xpcie_dma_core_ep dma_wdata<46>
Project.unit<0>.triggerChannel<0><7>=xpcie_dma_core_ep dma_waddr<7>
Project.unit<0>.triggerChannel<0><80>=xpcie_dma_core_ep dma_wdata<47>
Project.unit<0>.triggerChannel<0><81>=xpcie_dma_core_ep dma_wdata<48>
Project.unit<0>.triggerChannel<0><82>=xpcie_dma_core_ep dma_wdata<49>
Project.unit<0>.triggerChannel<0><83>=xpcie_dma_core_ep dma_wdata<50>
Project.unit<0>.triggerChannel<0><84>=xpcie_dma_core_ep dma_wdata<51>
Project.unit<0>.triggerChannel<0><85>=xpcie_dma_core_ep dma_wdata<52>
Project.unit<0>.triggerChannel<0><86>=xpcie_dma_core_ep dma_wdata<53>
Project.unit<0>.triggerChannel<0><87>=xpcie_dma_core_ep dma_wdata<54>
Project.unit<0>.triggerChannel<0><88>=xpcie_dma_core_ep dma_wdata<55>
Project.unit<0>.triggerChannel<0><89>=xpcie_dma_core_ep dma_wdata<56>
Project.unit<0>.triggerChannel<0><8>=xpcie_dma_core_ep dma_waddr<8>
Project.unit<0>.triggerChannel<0><90>=xpcie_dma_core_ep dma_wdata<57>
Project.unit<0>.triggerChannel<0><91>=xpcie_dma_core_ep dma_wdata<58>
Project.unit<0>.triggerChannel<0><92>=xpcie_dma_core_ep dma_wdata<59>
Project.unit<0>.triggerChannel<0><93>=xpcie_dma_core_ep dma_wdata<60>
Project.unit<0>.triggerChannel<0><94>=xpcie_dma_core_ep dma_wdata<61>
Project.unit<0>.triggerChannel<0><95>=xpcie_dma_core_ep dma_wdata<62>
Project.unit<0>.triggerChannel<0><96>=xpcie_dma_core_ep dma_wdata<63>
Project.unit<0>.triggerChannel<0><97>=xpcie_dma_core_ep dma_wdata_en
Project.unit<0>.triggerChannel<0><98>=xpcie_dma_core_ep dma_wdata_rdy
Project.unit<0>.triggerChannel<0><99>=xpcie_dma_core_ep dma_write_end
Project.unit<0>.triggerChannel<0><9>=xpcie_dma_core_ep dma_waddr<9>
Project.unit<0>.triggerChannel<1><0>=xpcie_dma_core_ep dma_raddr<0>
Project.unit<0>.triggerChannel<1><100>=xpcie_dma_core_ep dma_read_end
Project.unit<0>.triggerChannel<1><10>=xpcie_dma_core_ep dma_raddr<10>
Project.unit<0>.triggerChannel<1><11>=xpcie_dma_core_ep dma_raddr<11>
Project.unit<0>.triggerChannel<1><12>=xpcie_dma_core_ep dma_raddr<12>
Project.unit<0>.triggerChannel<1><13>=xpcie_dma_core_ep dma_raddr<13>
Project.unit<0>.triggerChannel<1><14>=xpcie_dma_core_ep dma_raddr<14>
Project.unit<0>.triggerChannel<1><15>=xpcie_dma_core_ep dma_raddr<15>
Project.unit<0>.triggerChannel<1><16>=xpcie_dma_core_ep dma_raddr<16>
Project.unit<0>.triggerChannel<1><17>=xpcie_dma_core_ep dma_raddr<17>
Project.unit<0>.triggerChannel<1><18>=xpcie_dma_core_ep dma_raddr<18>
Project.unit<0>.triggerChannel<1><19>=xpcie_dma_core_ep dma_raddr<19>
Project.unit<0>.triggerChannel<1><1>=xpcie_dma_core_ep dma_raddr<1>
Project.unit<0>.triggerChannel<1><20>=xpcie_dma_core_ep dma_raddr<20>
Project.unit<0>.triggerChannel<1><21>=xpcie_dma_core_ep dma_raddr<21>
Project.unit<0>.triggerChannel<1><22>=xpcie_dma_core_ep dma_raddr<22>
Project.unit<0>.triggerChannel<1><23>=xpcie_dma_core_ep dma_raddr<23>
Project.unit<0>.triggerChannel<1><24>=xpcie_dma_core_ep dma_raddr<24>
Project.unit<0>.triggerChannel<1><25>=xpcie_dma_core_ep dma_raddr<25>
Project.unit<0>.triggerChannel<1><26>=xpcie_dma_core_ep dma_raddr<26>
Project.unit<0>.triggerChannel<1><27>=xpcie_dma_core_ep dma_raddr<27>
Project.unit<0>.triggerChannel<1><28>=xpcie_dma_core_ep dma_raddr<28>
Project.unit<0>.triggerChannel<1><29>=xpcie_dma_core_ep dma_raddr<29>
Project.unit<0>.triggerChannel<1><2>=xpcie_dma_core_ep dma_raddr<2>
Project.unit<0>.triggerChannel<1><30>=xpcie_dma_core_ep dma_raddr<30>
Project.unit<0>.triggerChannel<1><31>=xpcie_dma_core_ep dma_raddr<31>
Project.unit<0>.triggerChannel<1><32>=xpcie_dma_core_ep dma_raddr_en
Project.unit<0>.triggerChannel<1><33>=xpcie_dma_core_ep dma_rdata<0>
Project.unit<0>.triggerChannel<1><34>=xpcie_dma_core_ep dma_rdata<1>
Project.unit<0>.triggerChannel<1><35>=xpcie_dma_core_ep dma_rdata<2>
Project.unit<0>.triggerChannel<1><36>=xpcie_dma_core_ep dma_rdata<3>
Project.unit<0>.triggerChannel<1><37>=xpcie_dma_core_ep dma_rdata<4>
Project.unit<0>.triggerChannel<1><38>=xpcie_dma_core_ep dma_rdata<5>
Project.unit<0>.triggerChannel<1><39>=xpcie_dma_core_ep dma_rdata<6>
Project.unit<0>.triggerChannel<1><3>=xpcie_dma_core_ep dma_raddr<3>
Project.unit<0>.triggerChannel<1><40>=xpcie_dma_core_ep dma_rdata<7>
Project.unit<0>.triggerChannel<1><41>=xpcie_dma_core_ep dma_rdata<8>
Project.unit<0>.triggerChannel<1><42>=xpcie_dma_core_ep dma_rdata<9>
Project.unit<0>.triggerChannel<1><43>=xpcie_dma_core_ep dma_rdata<10>
Project.unit<0>.triggerChannel<1><44>=xpcie_dma_core_ep dma_rdata<11>
Project.unit<0>.triggerChannel<1><45>=xpcie_dma_core_ep dma_rdata<12>
Project.unit<0>.triggerChannel<1><46>=xpcie_dma_core_ep dma_rdata<13>
Project.unit<0>.triggerChannel<1><47>=xpcie_dma_core_ep dma_rdata<14>
Project.unit<0>.triggerChannel<1><48>=xpcie_dma_core_ep dma_rdata<15>
Project.unit<0>.triggerChannel<1><49>=xpcie_dma_core_ep dma_rdata<16>
Project.unit<0>.triggerChannel<1><4>=xpcie_dma_core_ep dma_raddr<4>
Project.unit<0>.triggerChannel<1><50>=xpcie_dma_core_ep dma_rdata<17>
Project.unit<0>.triggerChannel<1><51>=xpcie_dma_core_ep dma_rdata<18>
Project.unit<0>.triggerChannel<1><52>=xpcie_dma_core_ep dma_rdata<19>
Project.unit<0>.triggerChannel<1><53>=xpcie_dma_core_ep dma_rdata<20>
Project.unit<0>.triggerChannel<1><54>=xpcie_dma_core_ep dma_rdata<21>
Project.unit<0>.triggerChannel<1><55>=xpcie_dma_core_ep dma_rdata<22>
Project.unit<0>.triggerChannel<1><56>=xpcie_dma_core_ep dma_rdata<23>
Project.unit<0>.triggerChannel<1><57>=xpcie_dma_core_ep dma_rdata<24>
Project.unit<0>.triggerChannel<1><58>=xpcie_dma_core_ep dma_rdata<25>
Project.unit<0>.triggerChannel<1><59>=xpcie_dma_core_ep dma_rdata<26>
Project.unit<0>.triggerChannel<1><5>=xpcie_dma_core_ep dma_raddr<5>
Project.unit<0>.triggerChannel<1><60>=xpcie_dma_core_ep dma_rdata<27>
Project.unit<0>.triggerChannel<1><61>=xpcie_dma_core_ep dma_rdata<28>
Project.unit<0>.triggerChannel<1><62>=xpcie_dma_core_ep dma_rdata<29>
Project.unit<0>.triggerChannel<1><63>=xpcie_dma_core_ep dma_rdata<30>
Project.unit<0>.triggerChannel<1><64>=xpcie_dma_core_ep dma_rdata<31>
Project.unit<0>.triggerChannel<1><65>=xpcie_dma_core_ep dma_rdata<32>
Project.unit<0>.triggerChannel<1><66>=xpcie_dma_core_ep dma_rdata<33>
Project.unit<0>.triggerChannel<1><67>=xpcie_dma_core_ep dma_rdata<34>
Project.unit<0>.triggerChannel<1><68>=xpcie_dma_core_ep dma_rdata<35>
Project.unit<0>.triggerChannel<1><69>=xpcie_dma_core_ep dma_rdata<36>
Project.unit<0>.triggerChannel<1><6>=xpcie_dma_core_ep dma_raddr<6>
Project.unit<0>.triggerChannel<1><70>=xpcie_dma_core_ep dma_rdata<37>
Project.unit<0>.triggerChannel<1><71>=xpcie_dma_core_ep dma_rdata<38>
Project.unit<0>.triggerChannel<1><72>=xpcie_dma_core_ep dma_rdata<39>
Project.unit<0>.triggerChannel<1><73>=xpcie_dma_core_ep dma_rdata<40>
Project.unit<0>.triggerChannel<1><74>=xpcie_dma_core_ep dma_rdata<41>
Project.unit<0>.triggerChannel<1><75>=xpcie_dma_core_ep dma_rdata<42>
Project.unit<0>.triggerChannel<1><76>=xpcie_dma_core_ep dma_rdata<43>
Project.unit<0>.triggerChannel<1><77>=xpcie_dma_core_ep dma_rdata<44>
Project.unit<0>.triggerChannel<1><78>=xpcie_dma_core_ep dma_rdata<45>
Project.unit<0>.triggerChannel<1><79>=xpcie_dma_core_ep dma_rdata<46>
Project.unit<0>.triggerChannel<1><7>=xpcie_dma_core_ep dma_raddr<7>
Project.unit<0>.triggerChannel<1><80>=xpcie_dma_core_ep dma_rdata<47>
Project.unit<0>.triggerChannel<1><81>=xpcie_dma_core_ep dma_rdata<48>
Project.unit<0>.triggerChannel<1><82>=xpcie_dma_core_ep dma_rdata<49>
Project.unit<0>.triggerChannel<1><83>=xpcie_dma_core_ep dma_rdata<50>
Project.unit<0>.triggerChannel<1><84>=xpcie_dma_core_ep dma_rdata<51>
Project.unit<0>.triggerChannel<1><85>=xpcie_dma_core_ep dma_rdata<52>
Project.unit<0>.triggerChannel<1><86>=xpcie_dma_core_ep dma_rdata<53>
Project.unit<0>.triggerChannel<1><87>=xpcie_dma_core_ep dma_rdata<54>
Project.unit<0>.triggerChannel<1><88>=xpcie_dma_core_ep dma_rdata<55>
Project.unit<0>.triggerChannel<1><89>=xpcie_dma_core_ep dma_rdata<56>
Project.unit<0>.triggerChannel<1><8>=xpcie_dma_core_ep dma_raddr<8>
Project.unit<0>.triggerChannel<1><90>=xpcie_dma_core_ep dma_rdata<57>
Project.unit<0>.triggerChannel<1><91>=xpcie_dma_core_ep dma_rdata<58>
Project.unit<0>.triggerChannel<1><92>=xpcie_dma_core_ep dma_rdata<59>
Project.unit<0>.triggerChannel<1><93>=xpcie_dma_core_ep dma_rdata<60>
Project.unit<0>.triggerChannel<1><94>=xpcie_dma_core_ep dma_rdata<61>
Project.unit<0>.triggerChannel<1><95>=xpcie_dma_core_ep dma_rdata<62>
Project.unit<0>.triggerChannel<1><96>=xpcie_dma_core_ep dma_rdata<63>
Project.unit<0>.triggerChannel<1><97>=xpcie_dma_core_ep dma_rdata_busy
Project.unit<0>.triggerChannel<1><98>=xpcie_dma_core_ep dma_rdata_en
Project.unit<0>.triggerChannel<1><99>=xpcie_dma_core_ep dma_rdata_rdy
Project.unit<0>.triggerChannel<1><9>=xpcie_dma_core_ep dma_raddr<9>
Project.unit<0>.triggerChannel<2><0>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<0>
Project.unit<0>.triggerChannel<2><10>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<10>
Project.unit<0>.triggerChannel<2><11>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<11>
Project.unit<0>.triggerChannel<2><12>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<12>
Project.unit<0>.triggerChannel<2><13>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<13>
Project.unit<0>.triggerChannel<2><14>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<14>
Project.unit<0>.triggerChannel<2><15>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<15>
Project.unit<0>.triggerChannel<2><16>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<16>
Project.unit<0>.triggerChannel<2><17>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<17>
Project.unit<0>.triggerChannel<2><18>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<18>
Project.unit<0>.triggerChannel<2><19>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<19>
Project.unit<0>.triggerChannel<2><1>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<1>
Project.unit<0>.triggerChannel<2><20>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<20>
Project.unit<0>.triggerChannel<2><21>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<21>
Project.unit<0>.triggerChannel<2><22>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<22>
Project.unit<0>.triggerChannel<2><23>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<23>
Project.unit<0>.triggerChannel<2><24>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<24>
Project.unit<0>.triggerChannel<2><25>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<25>
Project.unit<0>.triggerChannel<2><26>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<26>
Project.unit<0>.triggerChannel<2><27>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<27>
Project.unit<0>.triggerChannel<2><28>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<28>
Project.unit<0>.triggerChannel<2><29>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<29>
Project.unit<0>.triggerChannel<2><2>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<2>
Project.unit<0>.triggerChannel<2><30>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<30>
Project.unit<0>.triggerChannel<2><31>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<31>
Project.unit<0>.triggerChannel<2><32>=xpcie_dma_core_ep app PCIE_DMA dma_wdata_en
Project.unit<0>.triggerChannel<2><33>=xpcie_dma_core_ep app PCIE_DMA dma_wdata_rdy
Project.unit<0>.triggerChannel<2><34>=xpcie_dma_core_ep app PCIE_DMA dma_write_end
Project.unit<0>.triggerChannel<2><35>=xpcie_dma_core_ep app PCIE_DMA dma_write_start
Project.unit<0>.triggerChannel<2><3>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<3>
Project.unit<0>.triggerChannel<2><4>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<4>
Project.unit<0>.triggerChannel<2><5>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<5>
Project.unit<0>.triggerChannel<2><6>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<6>
Project.unit<0>.triggerChannel<2><7>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<7>
Project.unit<0>.triggerChannel<2><8>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<8>
Project.unit<0>.triggerChannel<2><9>=xpcie_dma_core_ep app PCIE_DMA dma_wdata<9>
Project.unit<0>.triggerChannel<3><0>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<0>
Project.unit<0>.triggerChannel<3><10>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<10>
Project.unit<0>.triggerChannel<3><11>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<11>
Project.unit<0>.triggerChannel<3><12>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<12>
Project.unit<0>.triggerChannel<3><13>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<13>
Project.unit<0>.triggerChannel<3><14>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<14>
Project.unit<0>.triggerChannel<3><15>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<15>
Project.unit<0>.triggerChannel<3><16>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<16>
Project.unit<0>.triggerChannel<3><17>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<17>
Project.unit<0>.triggerChannel<3><18>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<18>
Project.unit<0>.triggerChannel<3><19>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<19>
Project.unit<0>.triggerChannel<3><1>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<1>
Project.unit<0>.triggerChannel<3><20>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<20>
Project.unit<0>.triggerChannel<3><21>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<21>
Project.unit<0>.triggerChannel<3><22>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<22>
Project.unit<0>.triggerChannel<3><23>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<23>
Project.unit<0>.triggerChannel<3><24>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<24>
Project.unit<0>.triggerChannel<3><25>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<25>
Project.unit<0>.triggerChannel<3><26>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<26>
Project.unit<0>.triggerChannel<3><27>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<27>
Project.unit<0>.triggerChannel<3><28>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<28>
Project.unit<0>.triggerChannel<3><29>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<29>
Project.unit<0>.triggerChannel<3><2>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<2>
Project.unit<0>.triggerChannel<3><30>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<30>
Project.unit<0>.triggerChannel<3><31>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<31>
Project.unit<0>.triggerChannel<3><32>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<32>
Project.unit<0>.triggerChannel<3><33>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<33>
Project.unit<0>.triggerChannel<3><34>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<34>
Project.unit<0>.triggerChannel<3><35>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<35>
Project.unit<0>.triggerChannel<3><36>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<36>
Project.unit<0>.triggerChannel<3><37>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<37>
Project.unit<0>.triggerChannel<3><38>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<38>
Project.unit<0>.triggerChannel<3><39>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<39>
Project.unit<0>.triggerChannel<3><3>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<3>
Project.unit<0>.triggerChannel<3><40>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<40>
Project.unit<0>.triggerChannel<3><41>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<41>
Project.unit<0>.triggerChannel<3><42>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<42>
Project.unit<0>.triggerChannel<3><43>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<43>
Project.unit<0>.triggerChannel<3><44>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<44>
Project.unit<0>.triggerChannel<3><45>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<45>
Project.unit<0>.triggerChannel<3><46>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<46>
Project.unit<0>.triggerChannel<3><47>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<47>
Project.unit<0>.triggerChannel<3><48>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<48>
Project.unit<0>.triggerChannel<3><49>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<49>
Project.unit<0>.triggerChannel<3><4>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<4>
Project.unit<0>.triggerChannel<3><50>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<50>
Project.unit<0>.triggerChannel<3><51>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<51>
Project.unit<0>.triggerChannel<3><52>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<52>
Project.unit<0>.triggerChannel<3><53>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<53>
Project.unit<0>.triggerChannel<3><54>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<54>
Project.unit<0>.triggerChannel<3><55>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<55>
Project.unit<0>.triggerChannel<3><56>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<56>
Project.unit<0>.triggerChannel<3><57>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<57>
Project.unit<0>.triggerChannel<3><58>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<58>
Project.unit<0>.triggerChannel<3><59>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<59>
Project.unit<0>.triggerChannel<3><5>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<5>
Project.unit<0>.triggerChannel<3><60>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<60>
Project.unit<0>.triggerChannel<3><61>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<61>
Project.unit<0>.triggerChannel<3><62>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<62>
Project.unit<0>.triggerChannel<3><63>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<63>
Project.unit<0>.triggerChannel<3><64>=xpcie_dma_core_ep app PCIE_DMA dma_rdata_busy
Project.unit<0>.triggerChannel<3><65>=xpcie_dma_core_ep app PCIE_DMA dma_rdata_en
Project.unit<0>.triggerChannel<3><66>=xpcie_dma_core_ep app PCIE_DMA dma_read_end
Project.unit<0>.triggerChannel<3><67>=xpcie_dma_core_ep app PCIE_DMA dma_read_start
Project.unit<0>.triggerChannel<3><68>=xpcie_dma_core_ep app PCIE_DMA dma_reset
Project.unit<0>.triggerChannel<3><6>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<6>
Project.unit<0>.triggerChannel<3><7>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<7>
Project.unit<0>.triggerChannel<3><8>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<8>
Project.unit<0>.triggerChannel<3><9>=xpcie_dma_core_ep app PCIE_DMA dma_rdata<9>
Project.unit<0>.triggerChannel<4><0>=xpcie_dma_core_ep app PCIE_DMA trn_rd<0>
Project.unit<0>.triggerChannel<4><10>=xpcie_dma_core_ep app PCIE_DMA trn_rd<10>
Project.unit<0>.triggerChannel<4><11>=xpcie_dma_core_ep app PCIE_DMA trn_rd<11>
Project.unit<0>.triggerChannel<4><12>=xpcie_dma_core_ep app PCIE_DMA trn_rd<12>
Project.unit<0>.triggerChannel<4><13>=xpcie_dma_core_ep app PCIE_DMA trn_rd<13>
Project.unit<0>.triggerChannel<4><14>=xpcie_dma_core_ep app PCIE_DMA trn_rd<14>
Project.unit<0>.triggerChannel<4><15>=xpcie_dma_core_ep app PCIE_DMA trn_rd<15>
Project.unit<0>.triggerChannel<4><16>=xpcie_dma_core_ep app PCIE_DMA trn_rd<16>
Project.unit<0>.triggerChannel<4><17>=xpcie_dma_core_ep app PCIE_DMA trn_rd<17>
Project.unit<0>.triggerChannel<4><18>=xpcie_dma_core_ep app PCIE_DMA trn_rd<18>
Project.unit<0>.triggerChannel<4><19>=xpcie_dma_core_ep app PCIE_DMA trn_rd<19>
Project.unit<0>.triggerChannel<4><1>=xpcie_dma_core_ep app PCIE_DMA trn_rd<1>
Project.unit<0>.triggerChannel<4><20>=xpcie_dma_core_ep app PCIE_DMA trn_rd<20>
Project.unit<0>.triggerChannel<4><21>=xpcie_dma_core_ep app PCIE_DMA trn_rd<21>
Project.unit<0>.triggerChannel<4><22>=xpcie_dma_core_ep app PCIE_DMA trn_rd<22>
Project.unit<0>.triggerChannel<4><23>=xpcie_dma_core_ep app PCIE_DMA trn_rd<23>
Project.unit<0>.triggerChannel<4><24>=xpcie_dma_core_ep app PCIE_DMA trn_rd<24>
Project.unit<0>.triggerChannel<4><25>=xpcie_dma_core_ep app PCIE_DMA trn_rd<25>
Project.unit<0>.triggerChannel<4><26>=xpcie_dma_core_ep app PCIE_DMA trn_rd<26>
Project.unit<0>.triggerChannel<4><27>=xpcie_dma_core_ep app PCIE_DMA trn_rd<27>
Project.unit<0>.triggerChannel<4><28>=xpcie_dma_core_ep app PCIE_DMA trn_rd<28>
Project.unit<0>.triggerChannel<4><29>=xpcie_dma_core_ep app PCIE_DMA trn_rd<29>
Project.unit<0>.triggerChannel<4><2>=xpcie_dma_core_ep app PCIE_DMA trn_rd<2>
Project.unit<0>.triggerChannel<4><30>=xpcie_dma_core_ep app PCIE_DMA trn_rd<30>
Project.unit<0>.triggerChannel<4><31>=xpcie_dma_core_ep app PCIE_DMA trn_rd<31>
Project.unit<0>.triggerChannel<4><32>=xpcie_dma_core_ep app PCIE_DMA trn_rd<32>
Project.unit<0>.triggerChannel<4><33>=xpcie_dma_core_ep app PCIE_DMA trn_rd<33>
Project.unit<0>.triggerChannel<4><34>=xpcie_dma_core_ep app PCIE_DMA trn_rd<34>
Project.unit<0>.triggerChannel<4><35>=xpcie_dma_core_ep app PCIE_DMA trn_rd<35>
Project.unit<0>.triggerChannel<4><36>=xpcie_dma_core_ep app PCIE_DMA trn_rd<36>
Project.unit<0>.triggerChannel<4><37>=xpcie_dma_core_ep app PCIE_DMA trn_rd<37>
Project.unit<0>.triggerChannel<4><38>=xpcie_dma_core_ep app PCIE_DMA trn_rd<38>
Project.unit<0>.triggerChannel<4><39>=xpcie_dma_core_ep app PCIE_DMA trn_rd<39>
Project.unit<0>.triggerChannel<4><3>=xpcie_dma_core_ep app PCIE_DMA trn_rd<3>
Project.unit<0>.triggerChannel<4><40>=xpcie_dma_core_ep app PCIE_DMA trn_rd<40>
Project.unit<0>.triggerChannel<4><41>=xpcie_dma_core_ep app PCIE_DMA trn_rd<41>
Project.unit<0>.triggerChannel<4><42>=xpcie_dma_core_ep app PCIE_DMA trn_rd<42>
Project.unit<0>.triggerChannel<4><43>=xpcie_dma_core_ep app PCIE_DMA trn_rd<43>
Project.unit<0>.triggerChannel<4><44>=xpcie_dma_core_ep app PCIE_DMA trn_rd<44>
Project.unit<0>.triggerChannel<4><45>=xpcie_dma_core_ep app PCIE_DMA trn_rd<45>
Project.unit<0>.triggerChannel<4><46>=xpcie_dma_core_ep app PCIE_DMA trn_rd<46>
Project.unit<0>.triggerChannel<4><47>=xpcie_dma_core_ep app PCIE_DMA trn_rd<47>
Project.unit<0>.triggerChannel<4><48>=xpcie_dma_core_ep app PCIE_DMA trn_rd<48>
Project.unit<0>.triggerChannel<4><49>=xpcie_dma_core_ep app PCIE_DMA trn_rd<49>
Project.unit<0>.triggerChannel<4><4>=xpcie_dma_core_ep app PCIE_DMA trn_rd<4>
Project.unit<0>.triggerChannel<4><50>=xpcie_dma_core_ep app PCIE_DMA trn_rd<50>
Project.unit<0>.triggerChannel<4><51>=xpcie_dma_core_ep app PCIE_DMA trn_rd<51>
Project.unit<0>.triggerChannel<4><52>=xpcie_dma_core_ep app PCIE_DMA trn_rd<52>
Project.unit<0>.triggerChannel<4><53>=xpcie_dma_core_ep app PCIE_DMA trn_rd<53>
Project.unit<0>.triggerChannel<4><54>=xpcie_dma_core_ep app PCIE_DMA trn_rd<54>
Project.unit<0>.triggerChannel<4><55>=xpcie_dma_core_ep app PCIE_DMA trn_rd<55>
Project.unit<0>.triggerChannel<4><56>=xpcie_dma_core_ep app PCIE_DMA trn_rd<56>
Project.unit<0>.triggerChannel<4><57>=xpcie_dma_core_ep app PCIE_DMA trn_rd<57>
Project.unit<0>.triggerChannel<4><58>=xpcie_dma_core_ep app PCIE_DMA trn_rd<58>
Project.unit<0>.triggerChannel<4><59>=xpcie_dma_core_ep app PCIE_DMA trn_rd<59>
Project.unit<0>.triggerChannel<4><5>=xpcie_dma_core_ep app PCIE_DMA trn_rd<5>
Project.unit<0>.triggerChannel<4><60>=xpcie_dma_core_ep app PCIE_DMA trn_rd<60>
Project.unit<0>.triggerChannel<4><61>=xpcie_dma_core_ep app PCIE_DMA trn_rd<61>
Project.unit<0>.triggerChannel<4><62>=xpcie_dma_core_ep app PCIE_DMA trn_rd<62>
Project.unit<0>.triggerChannel<4><63>=xpcie_dma_core_ep app PCIE_DMA trn_rd<63>
Project.unit<0>.triggerChannel<4><64>=xpcie_dma_core_ep app PCIE_DMA trn_rsof_n
Project.unit<0>.triggerChannel<4><65>=xpcie_dma_core_ep app PCIE_DMA trn_reof_n
Project.unit<0>.triggerChannel<4><66>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<0>
Project.unit<0>.triggerChannel<4><67>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<1>
Project.unit<0>.triggerChannel<4><68>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<2>
Project.unit<0>.triggerChannel<4><69>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<3>
Project.unit<0>.triggerChannel<4><6>=xpcie_dma_core_ep app PCIE_DMA trn_rd<6>
Project.unit<0>.triggerChannel<4><70>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<4>
Project.unit<0>.triggerChannel<4><71>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<5>
Project.unit<0>.triggerChannel<4><72>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<6>
Project.unit<0>.triggerChannel<4><73>=xpcie_dma_core_ep app PCIE_DMA trn_rrem_n<7>
Project.unit<0>.triggerChannel<4><7>=xpcie_dma_core_ep app PCIE_DMA trn_rd<7>
Project.unit<0>.triggerChannel<4><8>=xpcie_dma_core_ep app PCIE_DMA trn_rd<8>
Project.unit<0>.triggerChannel<4><9>=xpcie_dma_core_ep app PCIE_DMA trn_rd<9>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerPortCount=5
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortWidth<0>=101
Project.unit<0>.triggerPortWidth<1>=101
Project.unit<0>.triggerPortWidth<2>=36
Project.unit<0>.triggerPortWidth<3>=69
Project.unit<0>.triggerPortWidth<4>=74
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
